### ISSUE TITLE
About visualization in the paper

### ISSUE THREAD

**Issue by Doctor-James** [PKUterran/NetlistGNN#3]
Hello, I have been reading the paper "Versatile Multi-stage Graph Neural Network for Circuit Representation" corresponding to your warehouse recently, and I have a question about visualization。The “figure 5: Visualization of congestion maps of circuit ispd2011/superblue19 produced by the baselines” . The congestion rate in the figure looks very high. The groud truth of congestion after I use dreamplace and ntcu is very sparse. I would like to ask you how the congestion is calculated in this figure

**Comment by PKUterran** [comment]
We exaggerate the congestion value to make the figure seem better
