### ISSUE TITLE
about data process

### ISSUE THREAD

**Issue by gjhhust** [PKUterran/NetlistGNN#5]
您好！我在复现您的论文途中遇到了不明白的地方，希望能得到您的解答，在准备模型数据的时候，需要dreamplace生成的数据，问题大致如下：

这是dreamplace收集到的信息，我查看了您再上一个issue中分享了您的合作朋友提交的dreamplace分支中保存了芯片数据如下：
![image](https://user-images.githubusercontent.com/73829930/230728829-23e9d8cd-fb96-48db-a4f5-da1ce22a948d.png)

我查看了NetListGNN中data/script_process.py生成数据集的部分代码，发现生成NetListGNN模型需要的数据，首先需要输入如下数据，我认为都是dreamplace产生的

```
1. /iter_' + str(z) + '_x.npy
2. /iter_' + str(z) + '_y.npy
3. /iter_fix_mapper.npy
4. '/iter_fix_po_x.npy', '/iter_fix_po_y.npy', '/iter_fix_pd.npy'
5. 'iter_fix_pin2edge.npy', 'iter_fix_pin2node.npy'
6. '/iter_fix_sizes_x.npy', '/iter_fix_sizes_y.npy'
7. '/iter_' + str(z)+ '_cmap_h', '/iter_' + str(z) + '_cmap_v' or '/iter_' + str(z)+ 'bad_cmap_h', '/iter_' + str(z) + 'bad_cmap_v' 
8. /vdm.npy /hdm.npy
9. 'iter_fix_hori_cap.npy', 'iter_fix_verti_cap.npy'
10. iter_fix_nctu_cap.npy
```
这些数据应该是dreamplace内收集好的，其中的有几个我对应不上dreamplace收集的信息，想咨询一下您
```

- iter_fix_mapper.npy、/iter_fix_pd.npy、iter_fix_pin2edge.npy、iter_fix_pin2node.npy
- iter_fix_hori_cap.npy、iter_fix_verti_cap.npy（这两个应该表示水平和垂直容量，和/vdm.npy /hdm.npy有区别吗）
- iter_fix_nctu_cap.npy
- '/iter_' + str(z)+ '_cmap_h', '/iter_' + str(z) + '_cmap_v' or '/iter_' + str(z)+ 'bad_cmap_h', '/iter_' + str(z) + 'bad_cmap_v' 

```
都是如何产生的呢，对应最上图的input或者output变量吗？或者是需要经过特别的运算？

**Comment by PKUterran** [comment]
见`data/script_process.py`

**Comment by PKUterran** [comment]
抱歉，我在这个工作中主要负责ML部分，对DREAMPlace和其他EDA的细节不了解，我咨询一下他们，请稍等几天。

**Comment by gjhhust** [comment]
感谢您的回复！期待！

**Comment by vz-2244** [comment]
你好，关于数据生产的问题：
1. iter_fix_mapper.npy 是所有的node到真实cell node的id映射（去除一些virtual node）。iter_fix_pd.npy是pin type（b'INPUT', b'OUTPUT', etc.).
2. 其他的这些数据的生产是在Dreamplace中添加了保存结果的接口，具体的代码改动如下：
![image](https://user-images.githubusercontent.com/79160952/230871117-445b6fa6-488f-4be6-b5b4-a59592bd97ec.png)
![image](https://user-images.githubusercontent.com/79160952/230871143-938ba41d-c8fd-4515-81f4-68ce06c10da1.png)

**Comment by gjhhust** [comment]
非常感谢您的帮助！那我没有问题了，将会关闭该issue

**Comment by gjhhust** [comment]
> 你好，关于数据生产的问题：
> 
> 1. iter_fix_mapper.npy 是所有的node到真实cell node的id映射（去除一些virtual node）。iter_fix_pd.npy是pin type（b'INPUT', b'OUTPUT', etc.).
> 2. 其他的这些数据的生产是在Dreamplace中添加了保存结果的接口，具体的代码改动如下：
>    ![image](https://user-images.githubusercontent.com/79160952/230871117-445b6fa6-488f-4be6-b5b4-a59592bd97ec.png)
>    ![image](https://user-images.githubusercontent.com/79160952/230871143-938ba41d-c8fd-4515-81f4-68ce06c10da1.png)

我在收集的时候发现bad_cmap和cmap用的都是一个rudy收集的拥塞数据，他们之间区别很重要吗，我没有很理解他们在NetlistGNN中的区别，我可以将cmap直接赋值给bad_cmap吗

**Comment by PKUterran** [comment]
一个是rudy跑的，一个是NCTUgr跑的

**Comment by gjhhust** [comment]
![image](https://user-images.githubusercontent.com/73829930/231451684-51a9b269-b185-43f5-9277-959aece7fdcb.png)

这是我自己提取得数据生成得process日志，能看看您生成数据集得日志吗，我想尽量复现数据集

还有我发现提取得nctu得cap和拥塞都是没有合并，维度相当于[731,567,9]或者[731,567,4]，而rudy提取得是将9层布线空间合并了是吗，相当于维度只有[731,567]

**Comment by Mayone0** [comment]
> 你好，关于数据生产的问题：
> 
> 1. iter_fix_mapper.npy 是所有的node到真实cell node的id映射（去除一些virtual node）。iter_fix_pd.npy是pin type（b'INPUT', b'OUTPUT', etc.).
> 2. 其他的这些数据的生产是在Dreamplace中添加了保存结果的接口，具体的代码改动如下：
>    ![image](https://user-images.githubusercontent.com/79160952/230871117-445b6fa6-488f-4be6-b5b4-a59592bd97ec.png)
>    ![image](https://user-images.githubusercontent.com/79160952/230871143-938ba41d-c8fd-4515-81f4-68ce06c10da1.png)

可以具体讲讲两个文件怎么修改的么，期待你的回复

**Comment by Mayone0** [comment]
> ![image](https://user-images.githubusercontent.com/73829930/231451684-51a9b269-b185-43f5-9277-959aece7fdcb.png)
> 
> 这是我自己提取得数据生成得process日志，能看看您生成数据集得日志吗，我想尽量复现数据集
> 
> 还有我发现提取得nctu得cap和拥塞都是没有合并，维度相当于[731,567,9]或者[731,567,4]，而rudy提取得是将9层布线空间合并了是吗，相当于维度只有[731,567]

您好我在用dreamplace处理dac2012 superblue2的数据时，关于cmap的数据一直无法收集到，是因为上面Llambda_metrics[-1][-1].overflow < params.node_area_adjust_overflow这条判断语句为0，即便注释掉也会导致其他问题，请问您是怎么收集到与cmap相关数据的

**Comment by hayaseyuukaa** [comment]
> > 你好，关于数据生产的问题：
> > 
> > 1. iter_fix_mapper.npy 是所有的node到真实cell node的id映射（去除一些virtual node）。iter_fix_pd.npy是pin type（b'INPUT', b'OUTPUT', etc.).
> > 2. 其他的这些数据的生产是在Dreamplace中添加了保存结果的接口，具体的代码改动如下：
> >    ![image](https://user-images.githubusercontent.com/79160952/230871117-445b6fa6-488f-4be6-b5b4-a59592bd97ec.png)
> >    ![image](https://user-images.githubusercontent.com/79160952/230871143-938ba41d-c8fd-4515-81f4-68ce06c10da1.png)
> 
> 可以具体讲讲两个文件怎么修改的么，期待你的回复

请问您已经解决了吗，可以分享下吗

**Comment by xiaoqiang88888** [comment]
@gjhhust @vz-2244 @Mayone0 几位老师好，请问您们是否已经解决了上述问题呢，我发现上述接口中nctugr的三个输出顺序（h，v，c）和初版dreamplace的输出顺序（map， h， v）这个是否存在区别呢。然后初版dreamplace用的是nctugr2.0

![Image](https://github.com/user-attachments/assets/cca32ca5-f9c6-49f6-8b9a-ed07dd26dfbd)

![Image](https://github.com/user-attachments/assets/d46e5394-8710-4279-80bb-036b48b39981) 

![Image](https://github.com/user-attachments/assets/b237c94a-7b0f-4ac7-8d3f-23f192b77748)

**Comment by xiaoqiang88888** [comment]
您好 请问 vdm 和hdm.npy 数据是哪里收集到的呢
